### ISSUE TITLE
Error when starting bot locally.

### ISSUE THREAD

**Issue by lastcoolnameleft** [fuselabs/echobot#3]
When I clone this repo and try to run locally, I get the following error.

```
$ node ./server.js
/Users/thfalgou/git/tmp/echobot/node_modules/botbuilder/lib/bots/ChatConnector.js:59
        var isEmulator = req.body['channelId'] === 'emulator';
                            ^

TypeError: Cannot read property 'body' of undefined
    at ChatConnector.verifyBotFramework (/Users/thfalgou/git/tmp/echobot/node_modules/botbuilder/lib/bots/ChatConnector.js:59:29)
    at Object.<anonymous> (/Users/thfalgou/git/tmp/echobot/server.js:24:40)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
```

Digging into the code, I believe that this is because server.js is not passing in expected req, res variables:

See:
https://github.com/fuselabs/echobot/blob/master/server.js#L24

https://github.com/Microsoft/BotBuilder/blob/master/Node/core/lib/bots/ChatConnector.js#L59

**Comment by lastcoolnameleft** [comment]
I'm baffled as to why this is happening on server.js startup opposed to waiting till the first request comes in; however, that might be something due to restify.

**Comment by danmarshall** [comment]
Do you have the latest code? I just checked in an update yesterday.

**Comment by lastcoolnameleft** [comment]
Yes.  I just found out about the repo today.  I've confirmed that HEAD points to dd52d6ff5a72a49451e5cd12f2612c69375a8bde.

To reproduce the problem, I run "git pull && rm -rf node_modules && npm install && npm start".

**Comment by lastcoolnameleft** [comment]
I just created https://github.com/fuselabs/echobot/pull/4 which fixes the problem for me.  I'm encountering this issue with Node v.6.6.0 after a clean clone and running "npm install && npm start"
